export const Root = '/'
export const Home = '/simple-spiders-admin'
export const JobScheduler = '/simple-spiders-admin/jobscheduler'
export const DataView = '/simple-spiders-admin/dataview'
export const History = '/simple-spiders-admin/history'